# Generated by Django 4.2.3 on 2023-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_active', models.BooleanField(default=False, verbose_name='邮箱是否已经验证')),
                ('avatar_url', models.CharField(default='', max_length=128, verbose_name='用户头像路径')),
                ('avatar', models.FileField(default='', upload_to='', verbose_name='用户头像')),
            ],
        ),
    ]
