# Generated by Django 4.2.3 on 2023-09-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='My_Game_Project_user',
        ),
    ]
