# Generated by Django 4.2.3 on 2023-09-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='defult@example.com', max_length=254, verbose_name='邮箱'),
        ),
    ]
